/**
 * Dijital Gru — 2026 Özel Günler Takvimi Veri Kümesi
 * Tüm aylar için kullanıcının sağladığı resmi, dini ve sosyal medya özel günleri.
 */

window.TAKVIM_DATA = [
    // OCAK 2026
    { month: 1, day: "1", title: "Yılbaşı", type: "Milli Gün", icon: "fa-champagne-glasses", color: "gold" },
    { month: 1, day: "2", title: "Bilim Kurgu Günü", type: "Sosyal Medya", icon: "fa-user-astronaut", color: "blue" },
    { month: 1, day: "6-12", title: "Verem Eğitimi ve Propaganda Haftası", type: "Sağlık", icon: "fa-lungs", color: "teal" },
    { month: 1, day: "7-14", title: "Beyaz Baston Körler Haftası", type: "Farkındalık", icon: "fa-eye-low-vision", color: "purple" },
    { month: 1, day: "10", title: "Dünya Gazeteciler Günü, Ziraat Mühendisleri Günü", type: "Sektörel", icon: "fa-newspaper", color: "blue" },
    { month: 1, day: "15", title: "Miraç Kandili", type: "Dini Gün", icon: "fa-moon", color: "gold" },
    { month: 1, day: "16", title: "Dünya Hijyen Günü", type: "Sağlık", icon: "fa-hands-bubbles", color: "teal" },
    { month: 1, day: "21", title: "Dünya Sarılma Günü", type: "Sosyal Medya", icon: "fa-heart", color: "red" },
    { month: 1, day: "24", title: "Dünya Karşılıksız İyilik Günü", type: "Farkındalık", icon: "fa-handshake-angle", color: "purple" },
    { month: 1, day: "24-31", title: "Dünya Cüzzam Haftası", type: "Sağlık", icon: "fa-house-medical", color: "teal" },
    { month: 1, day: "26", title: "Uluslararası Gümrük Günü", type: "Sektörel", icon: "fa-ship", color: "blue" },
    { month: 1, day: "27", title: "Dünya Cüzzam Günü", type: "Sağlık", icon: "fa-stethoscope", color: "teal" },
    { month: 1, day: "28", title: "Veri Koruma Günü", type: "Teknoloji", icon: "fa-shield-halved", color: "blue" },

    // ŞUBAT 2026
    { month: 2, day: "2", title: "Berat Kandili", type: "Dini Gün", icon: "fa-mosque", color: "gold" },
    { month: 2, day: "4", title: "Dünya Kanser Günü", type: "Sağlık", icon: "fa-ribbon", color: "purple" },
    { month: 2, day: "9", title: "Dünya Sigarayı Bırakma Günü, Dünya Pizza Günü", type: "Sosyal Medya", icon: "fa-pizza-slice", color: "red" },
    { month: 2, day: "13", title: "Dünya Radyo Günü", type: "Medya", icon: "fa-radio", color: "blue" },
    { month: 2, day: "14", title: "Sevgililer Günü, Dünya Öykü Günü", type: "Özel Gün", icon: "fa-heart-circle-bolt", color: "red" },
    { month: 2, day: "17", title: "Dünya Kediler Günü", type: "Sosyal Medya", icon: "fa-cat", color: "teal" },
    { month: 2, day: "19", title: "Ramazan Ayının Başlangıcı", type: "Dini Gün", icon: "fa-moon", color: "gold" },
    { month: 2, day: "27", title: "Dünya Ressamlar Günü", type: "Sanat", icon: "fa-palette", color: "purple" },
    { month: 2, day: "28", title: "Sivil Savunma Günü", type: "Milli Gün", icon: "fa-person-shield", color: "blue" },

    // MART 2026
    { month: 3, day: "1-7", title: "Yeşilay Haftası, Deprem Haftası, Girişimcilik Haftası", type: "Farkındalık", icon: "fa-leaf", color: "teal" },
    { month: 3, day: "3", title: "Dünya Kulak ve İşitme Günü", type: "Sağlık", icon: "fa-ear-listen", color: "teal" },
    { month: 3, day: "8", title: "Dünya Kadınlar Günü", type: "Özel Gün", icon: "fa-venus", color: "red" },
    { month: 3, day: "11-17", title: "Dünya Glokom Haftası, Dünya Tuza Dikkat Haftası", type: "Sağlık", icon: "fa-eye", color: "teal" },
    { month: 3, day: "8-14", title: "Bilim ve Teknoloji Haftası", type: "Teknoloji", icon: "fa-microchip", color: "blue" },
    { month: 3, day: "12", title: "İstiklâl Marşı’nın Kabulü ve M. Akif Ersoy’u Anma Günü, Dünya Glokom Günü, Dünya Böbrek Günü", type: "Milli Gelişim", icon: "fa-star-and-crescent", color: "red" },
    { month: 3, day: "14", title: "Tıp Bayramı", type: "Sektörel", icon: "fa-user-doctor", color: "blue" },
    { month: 3, day: "16", title: "Kadir Gecesi", type: "Dini Gün", icon: "fa-mosque", color: "gold" },
    { month: 3, day: "18", title: "Çanakkale Zaferi ve Şehitleri Anma Günü", type: "Milli Gün", icon: "fa-flag", color: "red" },
    { month: 3, day: "18-24", title: "Yaşlılara Saygı Haftası", type: "Toplumsal", icon: "fa-person-cane", color: "purple" },
    { month: 3, day: "19", title: "Ramazan Bayramı Arefesi", type: "Dini Gün", icon: "fa-clock", color: "gold" },
    { month: 3, day: "20-22", title: "Ramazan Bayramı", type: "Dini Gün", icon: "fa-hands-praying", color: "gold" },
    { month: 3, day: "21", title: "Nevruz Bayramı", type: "Kültürel", icon: "fa-seedling", color: "teal" },
    { month: 3, day: "21", title: "Dünya Down Sendromu Farkındalık Günü, Dünya Şiir Günü, Dünya Ormancılık Günü", type: "Çoklu Özel Gün", icon: "fa-tree", color: "purple" },
    { month: 3, day: "22", title: "Dünya Su Günü", type: "Çevre", icon: "fa-droplet", color: "teal" },
    { month: 3, day: "21-26", title: "Orman Haftası", type: "Çevre", icon: "fa-tree", color: "teal" },
    { month: 3, day: "23", title: "Dünya Meteoroloji Günü", type: "Bilimsel", icon: "fa-cloud-sun-rain", color: "blue" },
    { month: 3, day: "24", title: "Dünya Tüberküloz Günü", type: "Sağlık", icon: "fa-stethoscope", color: "teal" },
    { month: 3, day: "27", title: "Dünya Tiyatrolar Günü", type: "Kültür", icon: "fa-masks-theater", color: "purple" },
    { month: 3, day: "27-2", title: "Kütüphane Haftası", type: "Eğitim", icon: "fa-book-open", color: "blue" },

    // NİSAN 2026
    { month: 4, day: "1", title: "Dünya Şaka Günü", type: "Sosyal Medya", icon: "fa-face-laugh-squint", color: "red" },
    { month: 4, day: "1-7", title: "Kanserle Savaş Haftası", type: "Sağlık", icon: "fa-ribbon", color: "purple" },
    { month: 4, day: "2", title: "Dünya Otizm Farkındalık Günü", type: "Farkındalık", icon: "fa-puzzle-piece", color: "purple" },
    { month: 4, day: "4", title: "Dünya Sokak Hayvanları Günü", type: "Çevre", icon: "fa-paw", color: "teal" },
    { month: 4, day: "7", title: "Kişisel Verileri Koruma Günü", type: "Teknoloji", icon: "fa-user-shield", color: "blue" },
    { month: 4, day: "7-13", title: "Dünya Sağlık Haftası, Sağlık ve Sosyal Güvenlik Haftası", type: "Sağlık", icon: "fa-heart-pulse", color: "teal" },
    { month: 4, day: "10", title: "Polis Günü", type: "Resmi Gün", icon: "fa-shield", color: "blue" },
    { month: 4, day: "11", title: "Dünya Parkinson Hastalığı Günü", type: "Sağlık", icon: "fa-brain", color: "purple" },
    { month: 4, day: "12-18", title: "Kalp Sağlığı Haftası", type: "Sağlık", icon: "fa-heart", color: "teal" },
    { month: 4, day: "14-20", title: "Kutlu Doğum Haftası", type: "Dini Gün", icon: "fa-star", color: "gold" },
    { month: 4, day: "15", title: "Büyümenin İzlenmesi Günü", type: "Sağlık", icon: "fa-baby", color: "teal" },
    { month: 4, day: "15-21", title: "Malazgirt Haftası, Turizm Haftası", type: "Kültürel", icon: "fa-compass", color: "blue" },
    { month: 4, day: "17", title: "Dünya Hemofili Günü", type: "Sağlık", icon: "fa-kit-medical", color: "purple" },
    { month: 4, day: "19-25", title: "Kitap Günü ve Kütüphaneler Haftası", type: "Eğitim", icon: "fa-book", color: "blue" },
    { month: 4, day: "21-28", title: "Ebeler Haftası", type: "Sektörel", icon: "fa-hand-holding-heart", color: "teal" },
    { month: 4, day: "22", title: "Dünya Günü (Earth Day)", type: "Çevre", icon: "fa-earth-europe", color: "teal" },
    { month: 4, day: "23", title: "23 Nisan Ulusal Egemenlik ve Çocuk Bayramı", type: "Milli Bayram", icon: "fa-child-reaching", color: "red" },
    { month: 4, day: "24-30", title: "Aşı Haftası", type: "Sağlık", icon: "fa-syringe", color: "teal" },
    { month: 4, day: "25", title: "Dünya Veteriner Hekimliği Günü, Türkiye İstatistik Günü, Dünya Sıtma Günü", type: "Sektörel", icon: "fa-chart-pie", color: "blue" },
    { month: 4, day: "28", title: "Sağlıkçıya Şiddete Hayır Günü", type: "Toplumsal", icon: "fa-hand", color: "red" },
    { month: 4, day: "29", title: "Dünya Dans Günü", type: "Sanat", icon: "fa-person-dancing", color: "purple" },

    // MAYIS 2026
    { month: 5, day: "1", title: "Emek ve Dayanışma Günü", type: "Resmi Tatil", icon: "fa-hammer", color: "red" },
    { month: 5, day: "1-7", title: "Trafik ve İlkyardım Haftası", type: "Toplumsal", icon: "fa-traffic-light", color: "blue" },
    { month: 5, day: "2-10", title: "İş Güvenliği Haftası", type: "Sektörel", icon: "fa-helmet-safety", color: "blue" },
    { month: 5, day: "5", title: "Dünya Ebeler Günü", type: "Sektörel", icon: "fa-hand-holding-hand", color: "teal" },
    { month: 5, day: "5-6", title: "Hıdırellez", type: "Kültürel", icon: "fa-fire", color: "gold" },
    { month: 5, day: "7", title: "Dünya Astım Günü", type: "Sağlık", icon: "fa-wind", color: "purple" },
    { month: 5, day: "8", title: "Dünya Ebeveynler Günü, Dünya Talasemi Günü, Dünya Kızılay Kızılhaç Günü", type: "Çoklu Özel Gün", icon: "fa-people-group", color: "red" },
    { month: 5, day: "10-16", title: "Engelliler Haftası", type: "Toplumsal", icon: "fa-universal-access", color: "purple" },
    { month: 5, day: "10", title: "Anneler Günü, Dünya Sağlık İçin Hareket Et Günü, Dünya İnme Önleme Günü", type: "Özel Gün", icon: "fa-gift", color: "red" },
    { month: 5, day: "12", title: "Hemşireler Günü", type: "Sektörel", icon: "fa-user-nurse", color: "teal" },
    { month: 5, day: "12-18", title: "Hemşireler Haftası", type: "Sektörel", icon: "fa-stethoscope", color: "teal" },
    { month: 5, day: "15-21", title: "Gençlik Haftası", type: "Milli Gün", icon: "fa-child", color: "blue" },
    { month: 5, day: "17", title: "Dünya Hipertansiyon Günü", type: "Sağlık", icon: "fa-heart-pulse", color: "purple" },
    { month: 5, day: "18-24", title: "Müzeler Haftası", type: "Kültür", icon: "fa-monument", color: "purple" },
    { month: 5, day: "19", title: "Atatürk’ü Anma, Gençlik ve Spor Bayramı", type: "Milli Bayram", icon: "fa-person-running", color: "red" },
    { month: 5, day: "21", title: "Dünya Süt Günü", type: "Sağlık", icon: "fa-glass-water", color: "teal" },
    { month: 5, day: "22", title: "Avrupa Obezite Günü", type: "Sağlık", icon: "fa-weight-scale", color: "purple" },
    { month: 5, day: "25-31", title: "Avrupa Obezite Haftası", type: "Sağlık", icon: "fa-apple-whole", color: "teal" },
    { month: 5, day: "26", title: "Kurban Bayramı Arefesi", type: "Dini Gün", icon: "fa-clock", color: "gold" },
    { month: 5, day: "27-30", title: "Kurban Bayramı", type: "Dini Bayram", icon: "fa-mosque", color: "gold" },
    { month: 5, day: "29", title: "İstanbul’un Fethi", type: "Tarihi Gün", icon: "fa-fort-awesome", color: "red" },
    { month: 5, day: "31", title: "Dünya Sigara İçmeme Günü", type: "Sağlık", icon: "fa-ban-smoking", color: "teal" },

    // HAZİRAN 2026
    { month: 6, day: "1", title: "Dünya Çocuk Günü, Ulusal Fenilketonüri Günü", type: "Farkındalık", icon: "fa-children", color: "purple" },
    { month: 6, day: "1-7", title: "İyot Yetersizliği Hastalıklarının Önlenmesi Haftası", type: "Sağlık", icon: "fa-bottle-water", color: "teal" },
    { month: 6, day: "5", title: "Dünya Çevre Günü; Çevre Koruma Haftası (5-11 Haz)", type: "Çevre", icon: "fa-leaf", color: "teal" },
    { month: 6, day: "6", title: "Diyetisyenler Günü", type: "Sektörel", icon: "fa-carrot", color: "blue" },
    { month: 6, day: "8", title: "Dünya Okyanus Günü", type: "Çevre", icon: "fa-water", color: "teal" },
    { month: 6, day: "14", title: "Dünya Kan Bağışçıları Günü", type: "Sağlık", icon: "fa-droplet", color: "red" },
    { month: 6, day: "16", title: "Hicri Yılbaşı", type: "Dini Gün", icon: "fa-calendar-days", color: "gold" },
    { month: 6, day: "17", title: "Dünya Çölleşme ve Kuraklıkla Mücadele Günü", type: "Çevre", icon: "fa-sun", color: "teal" },
    { month: 6, day: "21", title: "Babalar Günü, Dünya ALS Günü", type: "Özel Gün", icon: "fa-user-tie", color: "red" },
    { month: 6, day: "21", title: "Yaz Gündönümü / En Uzun Gün", type: "Doğa Olayı", icon: "fa-umbrella-beach", color: "blue" },
    { month: 6, day: "25", title: "Aşure Günü", type: "Dini Gün", icon: "fa-bowl-food", color: "gold" },
    { month: 6, day: "26", title: "Dünya Uyuşturucu Kullanımı ile Mücadele Günü", type: "Toplumsal", icon: "fa-shield-halved", color: "blue" },

    // TEMMUZ 2026
    { month: 7, day: "1", title: "Kabotaj ve Deniz Bayramı", type: "Milli Bayram", icon: "fa-ship", color: "red" },
    { month: 7, day: "1-7", title: "Uluslararası Nasreddin Hoca Şenlikleri", type: "Kültür", icon: "fa-masks-theater", color: "purple" },
    { month: 7, day: "2", title: "Dünya UFO Günü", type: "Eğlenceli", icon: "fa-user-astronaut", color: "blue" },
    { month: 7, day: "6", title: "Dünya Öpücük Günü", type: "Sosyal Medya", icon: "fa-face-kiss-wink-heart", color: "red" },
    { month: 7, day: "7", title: "Dünya Çikolata Günü", type: "Sosyal Medya", icon: "fa-cookie", color: "gold" },
    { month: 7, day: "10", title: "Dünya Hukuk Günü", type: "Sektörel", icon: "fa-scale-balanced", color: "blue" },
    { month: 7, day: "11", title: "Dünya Nüfus Günü", type: "Toplumsal", icon: "fa-users-line", color: "blue" },
    { month: 7, day: "15", title: "Demokrasi ve Millî Birlik Günü", type: "Resmi Tatil", icon: "fa-building-columns", color: "red" },
    { month: 7, day: "17", title: "Dünya Emoji Günü", type: "Sosyal Medya", icon: "fa-face-smile-beam", color: "gold" },
    { month: 7, day: "20", title: "Uluslararası Satranç Günü", type: "Sosyal Medya", icon: "fa-chess", color: "purple" },
    { month: 7, day: "28", title: "Dünya Hepatit Günü", type: "Sağlık", icon: "fa-virus", color: "teal" },
    { month: 7, day: "30", title: "Dünya Arkadaşlık Günü", type: "Sosyal Medya", icon: "fa-user-group", color: "blue" },

    // AĞUSTOS 2026
    { month: 8, day: "16", title: "Türklerin Anadolu’da İlk Fetih Günü", type: "Tarihi Gün", icon: "fa-horse", color: "red" },
    { month: 8, day: "16-23", title: "Hacı Bektaş Veli’yi Anma Günü ve Haftası", type: "Kültür", icon: "fa-hand-peace", color: "purple" },
    { month: 8, day: "19", title: "Dünya İnsani Yardım Günü", type: "Toplumsal", icon: "fa-handshake-angle", color: "teal" },
    { month: 8, day: "24", title: "Mevlid Kandili", type: "Dini Gün", icon: "fa-mosque", color: "gold" },
    { month: 8, day: "30", title: "Zafer Bayramı", type: "Milli Bayram", icon: "fa-flag-usa", color: "red" }, // fallback flag icon handled gracefully

    // EYLÜL 2026
    { month: 9, day: "1", title: "Dünya Barış Günü", type: "Dünya Günü", icon: "fa-dove", color: "teal" },
    { month: 9, day: "3-9", title: "Halk Sağlığı Haftası", type: "Sağlık", icon: "fa-heart-pulse", color: "teal" },
    { month: 9, day: "8", title: "Dünya Okuma Yazma Günü, Dünya Fizyoterapi Günü", type: "Çoklu Özel Gün", icon: "fa-book-reader", color: "blue" },
    { month: 9, day: "10", title: "Dünya İntiharı Önleme Günü", type: "Sağlık", icon: "fa-brain", color: "purple" },
    { month: 9, day: "12", title: "Dünya İlk Yardım Günü", type: "Toplumsal", icon: "fa-kit-medical", color: "teal" },
    { month: 9, day: "14", title: "Dünya İlkyardım Günü", type: "Toplumsal", icon: "fa-kit-medical", color: "teal" },
    { month: 9, day: "15", title: "Lenfoma Günü", type: "Sağlık", icon: "fa-heart", color: "purple" },
    { month: 9, day: "19", title: "Gaziler Günü", type: "Milli Gün", icon: "fa-award", color: "red" },
    { month: 9, day: "21", title: "Uluslararası Barış Günü, Dünya Alzheimer Günü", type: "Çoklu Özel Gün", icon: "fa-hands-holding-heart", color: "purple" },
    { month: 9, day: "25", title: "Dünya Eczacılık Günü", type: "Sektörel", icon: "fa-prescription-bottle-medical", color: "blue" },
    { month: 9, day: "26", title: "Dil Bayramı, Dünya Doğum Kontrol Günü", type: "Kültürel", icon: "fa-language", color: "gold" },
    { month: 9, day: "27", title: "Dünya Turizm Günü", type: "Sektörel", icon: "fa-plane-departure", color: "blue" },
    { month: 9, day: "28", title: "Dünya Okul Sütü Günü", type: "Sağlık", icon: "fa-glass-water", color: "teal" },
    { month: 9, day: "29", title: "Dünya Kalp Günü", type: "Sağlık", icon: "fa-heart-circle-check", color: "red" },

    // EKİM 2026
    { month: 10, day: "1", title: "Dünya Kahve Günü; Dünya Vejetaryenler Günü; Dünya Yaşlılar Günü", type: "Çoklu Özel Gün", icon: "fa-coffee", color: "gold" },
    { month: 10, day: "1-31", title: "Meme Kanseri Bilinçlendirme Ayı", type: "Sağlık", icon: "fa-ribbon", color: "purple" },
    { month: 10, day: "1-7", title: "Emzirme Haftası", type: "Sağlık", icon: "fa-baby", color: "teal" },
    { month: 10, day: "2", title: "Uluslararası Şiddetsizlik Günü", type: "Toplumsal", icon: "fa-hand-peace", color: "teal" },
    { month: 10, day: "3", title: "Dünya Yürüyüş Günü", type: "Spor", icon: "fa-person-walking", color: "blue" },
    { month: 10, day: "4", title: "Hayvanları Koruma Günü; Dünya Mimarlık Günü", type: "Çoklu Özel Gün", icon: "fa-paw", color: "teal" },
    { month: 10, day: "10", title: "10.10 İndirim Günleri, Dünya Ruh Sağlığı Günü, Dünya Görme Günü", type: "Çoklu Özel Gün", icon: "fa-tags", color: "gold" },
    { month: 10, day: "11", title: "Dünya Kız Çocukları Günü", type: "Özel Gün", icon: "fa-child-dress", color: "red" },
    { month: 10, day: "12", title: "Dünya Artrit Günü", type: "Sağlık", icon: "fa-stethoscope", color: "purple" },
    { month: 10, day: "13", title: "Ankara’nın Başkent Oluşu, Uluslararası Afet Azaltma Günü", type: "Tarihi / Bilimsel", icon: "fa-building", color: "red" },
    { month: 10, day: "15", title: "Dünya El Yıkama Günü, Dünya Meme Sağlığı Günü", type: "Sağlık", icon: "fa-hands-bubbles", color: "teal" },
    { month: 10, day: "16", title: "Dünya Gıda Günü, Dünya Anestezi Günü", type: "Sağlık", icon: "fa-bowl-food", color: "teal" },
    { month: 10, day: "17", title: "Dünya Yoksullukla Mücadele Günü", type: "Toplumsal", icon: "fa-hand-holding-dollar", color: "blue" },
    { month: 10, day: "18", title: "Dünya Menopoz Günü", type: "Sağlık", icon: "fa-user-nurse", color: "purple" },
    { month: 10, day: "19-4", title: "Kızılay Haftası", type: "Toplumsal", icon: "fa-square-h", color: "red" },
    { month: 10, day: "20", title: "Dünya Osteoporoz Günü", type: "Sağlık", icon: "fa-bone", color: "purple" },
    { month: 10, day: "21", title: "Küresel İyot Eksikliği Günü", type: "Sağlık", icon: "fa-stethoscope", color: "teal" },
    { month: 10, day: "22", title: "Dünya Kekemelik Günü", type: "Farkındalık", icon: "fa-comment-slash", color: "purple" },
    { month: 10, day: "24", title: "Birleşmiş Milletler Günü", type: "Dünya Günü", icon: "fa-globe", color: "blue" },
    { month: 10, day: "26", title: "Hasta Hakları Günü", type: "Toplumsal", icon: "fa-hospital-user", color: "blue" },
    { month: 10, day: "29", title: "Cumhuriyet Bayramı", type: "Milli Bayram", icon: "fa-flag", color: "red" },
    { month: 10, day: "31", title: "Dünya Tasarruf Günü, Cadılar Bayramı (Halloween)", type: "Sosyal Medya", icon: "fa-ghost", color: "gold" },

    // KASIM 2026
    { month: 11, day: "1", title: "Türk Harf Devrimi’nin Kabulü", type: "Tarihi Gün", icon: "fa-pen-clip", color: "red" },
    { month: 11, day: "2-8", title: "Lösemili Çocuklar Haftası", type: "Sağlık", icon: "fa-ribbon", color: "red" },
    { month: 11, day: "3-9", title: "Organ Bağışı Haftası", type: "Sağlık", icon: "fa-lungs", color: "teal" },
    { month: 11, day: "6", title: "Dünya Şehircilik Günü", type: "Sektörel", icon: "fa-city", color: "blue" },
    { month: 11, day: "8", title: "Dünya Radyoloji Günü", type: "Sektörel", icon: "fa-x-ray", color: "blue" },
    { month: 11, day: "10", title: "Atatürk’ü Anma Günü", type: "Milli Anma", icon: "fa-star", color: "red" },
    { month: 11, day: "11", title: "11.11 Bekarlar Günü / Global Alışveriş Festivali", type: "E-ticaret", icon: "fa-cart-shopping", color: "gold" },
    { month: 11, day: "12", title: "Dünya Zatürre Günü, Afet Eğitimi Hazırlık Günü", type: "Sağlık", icon: "fa-kit-medical", color: "purple" },
    { month: 11, day: "14", title: "Dünya Diyabet Günü, Dünya Sinema Günü", type: "Çoklu Özel Gün", icon: "fa-film", color: "purple" },
    { month: 11, day: "17", title: "Dünya Akciğer Kanseri Günü, Dünya Prematüre Günü", type: "Sağlık", icon: "fa-lungs-virus", color: "purple" },
    { month: 11, day: "18", title: "Avrupa Antibiyotik Farkındalık Günü", type: "Sağlık", icon: "fa-pills", color: "teal" },
    { month: 11, day: "20", title: "Dünya Çocuk Hakları Günü, Dünya KOAH Günü", type: "Çoklu Özel Gün", icon: "fa-child-reaching", color: "blue" },
    { month: 11, day: "22", title: "Dünya Diş Hekimliği Günü", type: "Sektörel", icon: "fa-tooth", color: "blue" },
    { month: 11, day: "22-28", title: "Ağız ve Diş Sağlığı Haftası", type: "Sağlık", icon: "fa-toothbrush", color: "teal" },
    { month: 11, day: "24", title: "Öğretmenler Günü", type: "Özel Gün", icon: "fa-graduation-cap", color: "red" },
    { month: 11, day: "25", title: "Kadına Yönelik Şiddete Karşı Uluslararası Mücadele Günü", type: "Toplumsal", icon: "fa-hand", color: "red" },
    { month: 11, day: "27", title: "Black Friday (Kara Cuma İndirimleri)", type: "E-ticaret", icon: "fa-tags", color: "gold" },
    { month: 11, day: "30", title: "Cyber Monday (Siber Pazartesi)", type: "E-ticaret", icon: "fa-laptop-code", color: "blue" },

    // ARALIK 2026
    { month: 12, day: "1", title: "Dünya AIDS Günü", type: "Sağlık", icon: "fa-ribbon", color: "red" },
    { month: 12, day: "3", title: "Dünya Engelliler Günü", type: "Toplumsal", icon: "fa-universal-access", color: "purple" },
    { month: 12, day: "4", title: "Dünya Madenciler Günü", type: "Sektörel", icon: "fa-trowel-bricks", color: "blue" },
    { month: 12, day: "5", title: "Dünya Mühendisler Günü; Kadın Hakları Günü; Türk Kahvesi Günü; Dünya Toprak Günü", type: "Çoklu Özel Gün", icon: "fa-mug-hot", color: "gold" },
    { month: 12, day: "7", title: "Dünya Sivil Havacılık Günü", type: "Sektörel", icon: "fa-plane", color: "blue" },
    { month: 12, day: "10", title: "Üç Ayların Başlangıcı (Recep ayı) ve Regaip Kandili, İnsan Hakları Günü", type: "Dini / Toplumsal", icon: "fa-scale-balanced", color: "gold" },
    { month: 12, day: "15", title: "Uluslararası Çay Günü", type: "Sosyal Medya", icon: "fa-mug-saucer", color: "gold" },
    { month: 12, day: "21", title: "En Uzun Gece (Kış gündönümü)", type: "Doğa Olayı", icon: "fa-moon", color: "blue" }
];
